### ISSUE TITLE
marche pas

### ISSUE THREAD

**Issue by ClementV74** [Sarlay/fuckoff_kwyk#1]
salut sa ne marche pas pour moi, c patch ?

**Comment by Sarlay** [comment]
Salut,
Le script ne fait pas les kwyks automatiquement mais une popup si certaines conditions sont remplies (si il faut ajouter "y=" avant la réponse d'un exercice par exemple)

**Comment by ClementV74** [comment]
ok je vais test

**Comment by FeeGaffe** [comment]
c normal ? tu as discord au pire pour m'expliquer comment sa marche

![image](https://user-images.githubusercontent.com/45317801/166007658-d92095a1-182c-4431-aa58-223c657e9b85.png)

**Comment by FeeGaffe** [comment]
normal sa ? tu as discord au pire ?


![image](https://user-images.githubusercontent.com/45317801/166007873-52c5a17a-afd2-4042-8ade-22403ed17923.png)
